name: Deploy emendasmunicipais para Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instala dependências e faz build
        run: |
          npm ci
          npm run build

      - name: Deploy para Firebase Hosting (target: emendasmunicipais)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTAL_EMENDAS }}"
          projectId: portaldeemendas
          target: emendasmunicipais-target
